# Generated by Django 5.1.6 on 2025-03-02 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 2, 14, 39, 18, 45737, tzinfo=datetime.timezone.utc)),
        ),
    ]
