# Generated by Django 5.1.6 on 2025-03-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_contactus_options_alter_contactus_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/posts/%Y/%m/%d'),
        ),
    ]
